services:
  backend:
    build:
      context: ./backend
    container_name: gestao-financeira-backend
    ports:
      - "8085:8085"
    environment:
      PORT: 8085
      SUPABASE_URL: ${SUPABASE_URL}
      SUPABASE_ANON_KEY: ${SUPABASE_ANON_KEY}

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_BASE_URL: http://localhost:8085
        VITE_SUPABASE_URL: ${VITE_SUPABASE_URL}
        VITE_SUPABASE_ANON_KEY: ${VITE_SUPABASE_ANON_KEY}
    container_name: gestao-financeira-frontend
    ports:
      - "5173:80"
    depends_on:
      - backend